"""Tests for report continuity: dated plan carry-forward, snapshots, revisions."""

from datetime import date, datetime

from garmin_sync import temporal
from garmin_sync.ai.report_history import (
    build_continuity_section,
    build_snapshot,
    extract_plan,
    extract_plan_criteria,
    extract_verdict,
    find_revisions,
    save_snapshot,
)
from garmin_sync.db.models import Activity

NY = temporal.get_zone("America/New_York")

SUNDAY_REPORT = """# Fitness Analysis - Sunday, September 13, 2026

## 1. Today's call
Today: **Rest day, or at most 20–30 min very easy walk/spin only; no run.**

Key numbers: **RHR 75 (+30 vs baseline)**, **HRV 65 with 7-day trend -7.4%**.

## 2. Why
This is a **red-flag recovery day**, mainly because of the **massive RHR spike**.

## 3. Week ahead
- **Monday:** **Rest** or **20–30 min easy walk/spin + mobility** only.
- **Tuesday:** If morning markers normalize, do a **light re-entry run: 35–45 min easy Zone 2**.
- **Wednesday:** If Tuesday feels normal, **40–50 min easy run**.

**Morning signal that changes the plan:** resume running only if RHR is back near baseline. If RHR stays sharply elevated tomorrow, treat this as possible illness.

---
*Generated by garmin-sync AI analysis using gpt-5.4*
"""


def _detailed(rhr_sunday, sleep_sunday=None, load_sunday=None):
    return {
        "daily_rhr": [
            {"date": "2026-09-13", "value": rhr_sunday},
            {"date": "2026-09-12", "value": 43},
        ],
        "daily_hrv": [{"date": "2026-09-13", "value": 65.0}],
        "daily_sleep": [{"date": "2026-09-13", "hours": sleep_sunday}],
        "daily_body_battery": [],
        "daily_training_load": (
            [{"date": "2026-09-13", "load": load_sunday}] if load_sunday is not None else []
        ),
    }


def _snapshot(detailed, report_day, hour, minute):
    generated = datetime(report_day.year, report_day.month, report_day.day, hour, minute, tzinfo=NY)
    return build_snapshot(detailed, report_day, generated)


class TestExtractVerdict:
    """The daily-verdict extraction used for the recent-calls list."""

    def test_extracts_heading_style_verdict(self):
        text = (
            "# Fitness Analysis - Friday, September 11, 2026\n\n"
            "## Today: **Yellow-red for rest or very light recovery**\n"
            "This fits your usual Friday rest slot.\n"
        )
        assert extract_verdict(text) == "Yellow-red for rest or very light recovery"

    def test_extracts_today_line(self):
        text = (
            "## 1) Today's call\n"
            "Today: 40 min Z2 run with 4 strides\n"
            "Driven by HRV -2% and RHR at baseline.\n"
        )
        assert extract_verdict(text) == "40 min Z2 run with 4 strides"

    def test_returns_none_without_today_line(self):
        text = "RECOVERY STATUS\nHRV 81 ms (+15%)\nTRAINING LOAD\n"
        assert extract_verdict(text) is None

    def test_caps_verdict_length(self):
        verdict = extract_verdict("Today: " + "x" * 500)
        assert verdict is not None
        assert len(verdict) <= 140


class TestExtractPlan:
    def test_weekday_bullets_resolve_to_the_days_after_the_report(self):
        plan = extract_plan(SUNDAY_REPORT, date(2026, 9, 13))
        assert [day for day, _ in plan] == [date(2026, 9, 14), date(2026, 9, 15), date(2026, 9, 16)]
        assert plan[0][1] == "Rest or 20–30 min easy walk/spin + mobility only."
        assert all("**" not in text for _, text in plan)

    def test_dated_bullets_and_relative_words_are_pinned(self):
        report = (
            "## 3. Week ahead\n"
            "- **Tue Sep 15:** If today feels normal, 40–50 min easy run.\n"
            "- **Wed, Sep 16:** Tempo inside a 60 min run.\n"
        )
        assert extract_plan(report, date(2026, 9, 14)) == [
            (date(2026, 9, 15), "If today [Mon Sep 14] feels normal, 40–50 min easy run."),
            (date(2026, 9, 16), "Tempo inside a 60 min run."),
        ]

    def test_only_reads_the_week_ahead_section(self):
        report = (
            "## 1. Today's call\n- **Tuesday:** not a plan line\n"
            "## 6) Week ahead: recommended adjustment\n"
            "### Suggested approach\n"
            "- **Saturday:** easy long run only\n"
            "- keep all other runs easy\n"
            "## 7) Alerts\n- **Sunday:** not a plan line either\n"
        )
        assert extract_plan(report, date(2026, 9, 11)) == [(date(2026, 9, 12), "easy long run only")]

    def test_year_rollover(self):
        report = "## Week ahead\n- **Fri Jan 1:** Easy run\n"
        assert extract_plan(report, date(2026, 12, 31)) == [(date(2027, 1, 1), "Easy run")]

    def test_bold_section_titles(self):
        # The format gpt-5.4 produced in the Sep 14 replay: bold titles, no headings
        report = (
            "**Today's call**  \n"
            "Today: Rest day, or at most 20–30 min very easy walk/spin; no run.  \n\n"
            "**Why**  \n"
            "- **Tuesday:** not a plan line\n\n"
            "**Week ahead**  \n"
            "- **Tue Sep 15:** 35–45 min easy Zone 2 run only.  \n"
            "- **Wed Sep 16:** 40–50 min easy run.  \n\n"
            "Morning signal that changes the plan: hold if resting HR is >+5 bpm.\n"
        )
        assert extract_plan(report, date(2026, 9, 14)) == [
            (date(2026, 9, 15), "35–45 min easy Zone 2 run only."),
            (date(2026, 9, 16), "40–50 min easy run."),
        ]
        assert extract_plan_criteria(report, date(2026, 9, 14)) == "hold if resting HR is >+5 bpm."

    def test_plan_change_criteria_pins_relative_words(self):
        criteria = extract_plan_criteria(SUNDAY_REPORT, date(2026, 9, 13))
        assert criteria.startswith("resume running only if RHR is back near baseline")
        assert "tomorrow [Mon Sep 14]" in criteria


class TestRevisions:
    def test_revision_on_the_report_day_is_reported(self):
        sunday = _snapshot(_detailed(75), date(2026, 9, 13), 10, 1)
        monday = _snapshot(_detailed(47), date(2026, 9, 14), 8, 2)
        assert find_revisions(sunday, monday, date(2026, 9, 14)) == [
            "Sun Sep 13 (yesterday) resting HR: 75 bpm at report time, now 47 bpm "
            "(that day was still in progress when the report ran)"
        ]

    def test_small_changes_and_accumulating_load_are_ignored(self):
        sunday = _snapshot(_detailed(45, load_sunday=27), date(2026, 9, 13), 10, 1)
        monday = _snapshot(_detailed(47, load_sunday=284), date(2026, 9, 14), 8, 2)
        assert find_revisions(sunday, monday, date(2026, 9, 14)) == []

    def test_value_missing_at_report_time(self):
        before = _snapshot(_detailed(43, sleep_sunday=None), date(2026, 9, 14), 8, 2)
        after = _snapshot(_detailed(43, sleep_sunday=6.5), date(2026, 9, 15), 8, 2)
        assert find_revisions(before, after, date(2026, 9, 15)) == [
            "Sun Sep 13 (2 days ago) sleep: not recorded at report time, now 6.5 h"
        ]


class TestContinuitySection:
    def test_sunday_to_monday(self, tmp_path):
        (tmp_path / "analysis-2026-09-13.md").write_text(SUNDAY_REPORT)
        save_snapshot(tmp_path, _snapshot(_detailed(75), date(2026, 9, 13), 10, 1))
        monday = _snapshot(_detailed(47), date(2026, 9, 14), 8, 2)
        recorded = {
            date(2026, 9, 13): [
                Activity(
                    activity_id="run",
                    activity_type="running",
                    start_time="2026-09-13T15:14:05",
                    start_time_local="2026-09-13 11:14:05",
                    duration_seconds=2760,
                    training_load=176.0,
                ),
                Activity(
                    activity_id="cardio",
                    activity_type="indoor_cardio",
                    start_time="2026-09-13T14:52:57",
                    start_time_local="2026-09-13 10:52:57",
                    duration_seconds=300,
                    training_load=27.0,
                ),
            ],
        }

        section = build_continuity_section(
            tmp_path,
            date(2026, 9, 14),
            monday,
            lambda day: recorded.get(day, []),
            tz_name="America/New_York",
        )

        assert "- Sun Sep 13 (yesterday): Rest day, or at most 20–30 min very easy walk/spin only; no run" in section
        assert (
            "- Sun Sep 13 (yesterday): indoor cardio 5 min at 10:52 AM; "
            "running 46 min at 11:14 AM (total load 203)"
        ) in section
        assert '<previous_plan written="Sun Sep 13, 10:01 AM EDT">' in section
        assert "- Mon Sep 14 (today): Rest or 20–30 min easy walk/spin + mobility only." in section
        assert "- Tue Sep 15 (tomorrow): If morning markers normalize" in section
        assert "Plan-change criteria: resume running only if" in section
        assert "resting HR: 75 bpm at report time, now 47 bpm" in section
        # The previous report's prose and stale numbers are never re-injected.
        assert "RHR 75 (+30 vs baseline)" not in section
        assert "red-flag" not in section

    def test_no_prior_reports(self, tmp_path):
        assert build_continuity_section(tmp_path, date(2026, 9, 14), {"metrics": {}}, lambda day: []) is None
